### ISSUE TITLE
AttributeError: 'CUDALongTensor' object has no attribute 'T'

### ISSUE THREAD

**Issue by kaih70** [jeffreysijuntan/CryptGPU#1]
Hi, I am trying to install CryptGPU on Ubuntu 16.04.6 LTS with CUDA Version: 10.1.
Other environmental dependency:
gcc4.8.5
python3.8
protobuf-3.17.3.

It seems that `python3 setup.py install` installs torch 1.6.0 which is not adaptable with CUDA 10.1.
So I installed torch==1.6.0+cu101 instead.

Also  `python3 setup.py install` provides an onnx with some symbol linking problem.
I reinstalled from pip instead.

Then I tried `python3 scripts/benchmark.py --exp inference_all`

Here is what I got:
```
INFO:root:==================
INFO:root:DistributedCommunicator with rank 1
INFO:root:==================
INFO:root:==================
INFO:root:DistributedCommunicator with rank 2
INFO:root:==================
INFO:root:==================
INFO:root:DistributedCommunicator with rank 0
INFO:root:==================
INFO:root:World size = 3
INFO:root:World size = 3
INFO:root:World size = 3
Running inference on mnist dataset with lenet network
/usr/local/lib/python3.8/site-packages/cryptgpu-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py:148: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
/usr/local/lib/python3.8/site-packages/cryptgpu-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py:148: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
/usr/local/lib/python3.8/site-packages/cryptgpu-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py:148: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
Process process 2:
Process process 0:
Process process 1:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/CryptGPU/scripts/multiprocess_launcher.py", line 62, in _run_process
    run_process_fn()
  File "/root/CryptGPU/scripts/benchmark.py", line 272, in inference_all
    inference(model, input_size, device="cuda")
  File "/root/CryptGPU/scripts/benchmark.py", line 36, in inference
    model.replicate_parameters()
  File "/usr/local/lib/python3.8/site-packages/cryptgpu-0.1.0-py3.8.egg/crypten/nn/module.py", line 459, in replicate_parameters
    module.replicate_parameters()
  File "/usr/local/lib/python3.8/site-packages/cryptgpu-0.1.0-py3.8.egg/crypten/nn/module.py", line 452, in replicate_parameters
    share = share.T
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/root/CryptGPU/scripts/multiprocess_launcher.py", line 62, in _run_process
    run_process_fn()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
AttributeError: 'CUDALongTensor' object has no attribute 'T'
  File "/root/CryptGPU/scripts/benchmark.py", line 272, in inference_all
    inference(model, input_size, device="cuda")
  File "/root/CryptGPU/scripts/multiprocess_launcher.py", line 62, in _run_process
    run_process_fn()
  File "/root/CryptGPU/scripts/benchmark.py", line 36, in inference
    model.replicate_parameters()
  File "/root/CryptGPU/scripts/benchmark.py", line 272, in inference_all
    inference(model, input_size, device="cuda")
  File "/usr/local/lib/python3.8/site-packages/cryptgpu-0.1.0-py3.8.egg/crypten/nn/module.py", line 459, in replicate_parameters
    module.replicate_parameters()
  File "/root/CryptGPU/scripts/benchmark.py", line 36, in inference
    model.replicate_parameters()
  File "/usr/local/lib/python3.8/site-packages/cryptgpu-0.1.0-py3.8.egg/crypten/nn/module.py", line 452, in replicate_parameters
    share = share.T
  File "/usr/local/lib/python3.8/site-packages/cryptgpu-0.1.0-py3.8.egg/crypten/nn/module.py", line 459, in replicate_parameters
    module.replicate_parameters()
  File "/usr/local/lib/python3.8/site-packages/cryptgpu-0.1.0-py3.8.egg/crypten/nn/module.py", line 452, in replicate_parameters
    share = share.T
AttributeError: 'CUDALongTensor' object has no attribute 'T'
AttributeError: 'CUDALongTensor' object has no attribute 'T'
Traceback (most recent call last):
  File "scripts/benchmark.py", line 360, in <module>
    launcher.join()
  File "/root/CryptGPU/scripts/multiprocess_launcher.py", line 73, in join
    assert (
AssertionError: process 0 has non-zero exit code 1
```

Did I do anything wrong with installation?
Or is there any docker image works?
Any advice?

Looking forward to your reply.

**Comment by jeffreysijuntan** [comment]
Hi, thanks for raising this issue. To fix this issue, change `share = share.T` to `share = share.transpose(0,1)`. 

We just pushed a new commit for the fix so you can pull the latest commit and reinstall. Hope this fix will address your issue.

**Comment by kaih70** [comment]
It works.
Thank you!
